import express from 'express';
import path from 'path';
import { createServer as createViteServer } from 'vite';
import * as XLSX from 'xlsx';
import nodemailer from 'nodemailer';
import { createClient } from '@supabase/supabase-js';
import { setupPatientAccessRoutesV2 } from './src/server/patientAccessV2';

const supabaseUrl = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || 'https://ctllgomqzeweeyrvxboc.supabase.co';
const supabasePublishableKey = process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_ANON_KEY || '';
const supabaseSecretKey = process.env.SUPABASE_SECRET_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY || '';
const supabaseServer = createClient(supabaseUrl, supabasePublishableKey);
const EMAIL_REGEX = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$/;

async function startServer(){
 const app=express();const PORT=3000;app.use(express.json({limit:'15mb'}));
 app.post('/api/send-email',async(req,res)=>{try{const h=req.headers.authorization;if(!h?.startsWith('Bearer '))return res.status(401).json({success:false,error:'ไม่ได้รับอนุญาต'});const token=h.slice(7).trim();const {data:{user},error}=await supabaseServer.auth.getUser(token);if(error||!user)return res.status(401).json({success:false,error:'เซสชันหมดอายุหรือไม่ถูกต้อง'});const {recipientEmail,subject='รายงานข้อมูลผลการตรวจสุขภาพ อสม.',records=[],vhvProfile={},fileName='ค่าวัดสุขภาพ_อสม',customNote=''}=req.body;if(!recipientEmail||typeof recipientEmail!=='string'||!EMAIL_REGEX.test(recipientEmail.trim()))return res.status(400).json({success:false,error:'กรุณาระบุอีเมลผู้รับที่ถูกต้อง'});if(!Array.isArray(records)||!records.length)return res.status(400).json({success:false,error:'ไม่พบรายการข้อมูลผลการตรวจสุขภาพ'});const rows=records.map((r:any,i:number)=>({'ลำดับ':i+1,'วันที่ตรวจ':r.date||'','เวลา':r.time||'','เลขบัตรประชาชน':r.citizenIdCard||r.idCard||'-','ชื่อ':r.citizenFirstName||'','นามสกุล':r.citizenLastName||'','เพศ':r.gender||'','อายุ':r.citizenAge??'','ค่าบน SYS':r.systolic??'','ค่าล่าง DIA':r.diastolic??'','ชีพจร':r.pulse??'','น้ำหนัก':r.weight??'','ส่วนสูง':r.height??'','BMI':r.bmi??'','น้ำตาล FBS':r.bloodSugar??'','อุณหภูมิ':r.temperature??'','หมายเหตุ':r.notes||''}));const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'RawHealthData');const buffer=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});const safe=`${String(fileName).replace(/[^a-zA-Z0-9_\u0E00-\u0E7F-]/g,'_')}.xlsx`;const html=`<div style="font-family:Arial,sans-serif"><h2>${subject}</h2><p>จำนวนรายการ: ${records.length}</p><p>${customNote||''}</p><p>ผู้ส่ง: ${vhvProfile.name||'อสม.'}</p></div>`;let previewUrl:null|string=null;if(process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS){const transporter=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT)||587,secure:(Number(process.env.SMTP_PORT)||587)===465,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});const info=await transporter.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:recipientEmail.trim(),subject,html,attachments:[{filename:safe,content:buffer,contentType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}]});previewUrl=nodemailer.getTestMessageUrl(info)||null;}return res.json({success:true,recipient:recipientEmail.trim(),fileName:safe,recordsCount:records.length,previewUrl});}catch(e:any){console.error(e);return res.status(500).json({success:false,error:e?.message||'เกิดข้อผิดพลาดในการส่งอีเมล'});}});
 setupPatientAccessRoutesV2(app,supabaseServer,supabaseUrl,supabasePublishableKey,supabaseSecretKey||undefined);
 if(process.env.NODE_ENV==='production'&&!supabaseSecretKey)throw new Error('SUPABASE_SECRET_KEY is required in production for patient access');
 if(process.env.NODE_ENV!=='production'){const vite=await createViteServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);}else{const distPath=path.join(process.cwd(),'dist');app.use(express.static(distPath));app.get('*',(req,res)=>res.sendFile(path.join(distPath,'index.html')));}app.listen(PORT,'0.0.0.0',()=>console.log(`Server running on http://localhost:${PORT}`));}
startServer();
