import { FormEvent, useState } from 'react';
import { Activity, CalendarDays, ChevronRight, HeartPulse, LockKeyhole, ShieldCheck, UserRound } from 'lucide-react';

type View = 'home' | 'health' | 'profile';
const mockRecords = [{date:'7 ก.ย. 2569',bp:'118/76',pulse:72,weight:64.2,glucose:96},{date:'12 มิ.ย. 2569',bp:'121/79',pulse:75,weight:65.1,glucose:101},{date:'15 มี.ค. 2569',bp:'124/81',pulse:78,weight:65.8,glucose:98}];

export default function App(){
 const params=new URLSearchParams(window.location.search); const [token,setToken]=useState(params.get('token')||''); const [pin,setPin]=useState(''); const [authenticated,setAuthenticated]=useState(!!sessionStorage.getItem('vhv_patient_access')); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [view,setView]=useState<View>('home');
 async function submit(e:FormEvent){e.preventDefault();setError('');if(!token.trim()||!/^[0-9]{6}$/.test(pin)){setError('กรุณากรอกลิงก์รหัสเข้าถึงและ PIN 6 หลัก');return}setLoading(true);try{const r=await fetch('/api/patient-access/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:token.trim(),pin:pin.trim()})});const d=await r.json().catch(()=>null);if(!r.ok||!d?.success)throw new Error(d?.error||'ไม่สามารถตรวจสอบสิทธิ์ได้');sessionStorage.setItem('vhv_patient_access',JSON.stringify({verifiedAt:Date.now(),access:d.access||null}));setAuthenticated(true)}catch(x){setError(x instanceof Error?x.message:'ไม่สามารถตรวจสอบสิทธิ์ได้')}finally{setLoading(false)}}
 if(!authenticated)return <div className="login-page"><div className="login-card"><div className="brand-mark large"><HeartPulse size={28}/></div><p className="eyebrow">VHV Patient Access</p><h1>เข้าถึงข้อมูลสุขภาพ</h1><p className="login-copy">กรอกรหัส PIN 6 หลักที่ได้รับจากเจ้าหน้าที่ เพื่อดูข้อมูลสุขภาพของคุณ</p><form onSubmit={submit}>{!token&&<label>รหัสเข้าถึง<input value={token} onChange={e=>setToken(e.target.value)} placeholder="วางลิงก์รหัสเข้าถึง" autoComplete="off"/></label>}<label>PIN 6 หลัก<input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="••••••" inputMode="numeric" maxLength={6} autoComplete="one-time-code"/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={loading}>{loading?'กำลังตรวจสอบ…':'เข้าสู่ข้อมูลสุขภาพ'}</button></form><div className="secure-note"><LockKeyhole size={17}/>การเข้าถึงได้รับการป้องกันและมีวันหมดอายุ</div><div className="privacy"><ShieldCheck size={17}/>อย่าแชร์ PIN หรือ QR ของคุณกับผู้อื่น</div></div></div>;
 const latest=mockRecords[0]; const logout=()=>{sessionStorage.removeItem('vhv_patient_access');setAuthenticated(false);setPin('')};
 return <div className="app"><header className="topbar"><div className="brand"><div className="brand-mark"><HeartPulse size={22}/></div><div><b>VHV Patient Access</b><span>ข้อมูลสุขภาพของฉัน</span></div></div><button className="logout" onClick={logout}>ออกจากระบบ</button></header><main><section className="welcome"><div><p className="eyebrow">พื้นที่ส่วนตัว</p><h1>{view==='home'?'สุขภาพของฉัน':view==='health'?'ประวัติสุขภาพ':'ข้อมูลส่วนตัว'}</h1><p>ดูข้อมูลสุขภาพของคุณได้ในที่เดียว</p></div><div className="privacy"><ShieldCheck size={18}/>ข้อมูลของคุณเป็นส่วนตัว</div></section>
 {view==='home'&&<><div className="cards"><Metric icon={<HeartPulse/>} label="ความดันล่าสุด" value={latest.bp} unit="mmHg"/><Metric icon={<Activity/>} label="ชีพจร" value={latest.pulse} unit="ครั้ง/นาที"/><Metric icon={<Activity/>} label="น้ำหนัก" value={latest.weight} unit="กก."/><Metric icon={<Activity/>} label="น้ำตาล" value={latest.glucose} unit="mg/dL"/></div><div className="grid-2"><Panel title="การตรวจสุขภาพล่าสุด" icon={<CalendarDays/>}><div className="record-highlight"><div><span>วันที่ตรวจ</span><strong>{latest.date}</strong></div><div className="status">บันทึกแล้ว</div></div><Row label="ความดันโลหิต" value={`${latest.bp} mmHg`}/><Row label="ชีพจร" value={`${latest.pulse} ครั้ง/นาที`}/><Row label="น้ำหนัก" value={`${latest.weight} กก.`}/><button className="link-btn" onClick={()=>setView('health')}>ดูประวัติทั้งหมด <ChevronRight size={17}/></button></Panel><Panel title="ข้อมูลส่วนตัว" icon={<UserRound/>}><Row label="ชื่อ-นามสกุล" value="ผู้รับบริการ"/><Row label="วันเกิด" value="•• / •• / ••••"/><Row label="สถานะ" value="ผู้รับบริการ"/><button className="link-btn" onClick={()=>setView('profile')}>ดูข้อมูลส่วนตัว <ChevronRight size={17}/></button></Panel></div></>}
 {view==='health'&&<Panel title="ประวัติการตรวจสุขภาพ" icon={<Activity/>}><div className="table-wrap"><table><thead><tr><th>วันที่</th><th>ความดัน</th><th>ชีพจร</th><th>น้ำหนัก</th><th>น้ำตาล</th></tr></thead><tbody>{mockRecords.map(r=><tr key={r.date}><td>{r.date}</td><td>{r.bp}</td><td>{r.pulse}</td><td>{r.weight}</td><td>{r.glucose}</td></tr>)}</tbody></table></div></Panel>}
 {view==='profile'&&<Panel title="ข้อมูลส่วนตัว" icon={<UserRound/>}><div className="profile-grid"><Info label="ชื่อ-นามสกุล" value="ผู้รับบริการ"/><Info label="วันเกิด" value="ไม่แสดงในตัวอย่าง"/><Info label="เบอร์โทรศัพท์" value="••••••••••"/><Info label="เลขประจำตัว" value="•••••••••••••"/></div><div className="notice"><ShieldCheck size={19}/>ข้อมูลระบุตัวตนบางส่วนถูกซ่อนเพื่อความเป็นส่วนตัว</div></Panel>}</main><nav className="bottom-nav"><button className={view==='home'?'active':''} onClick={()=>setView('home')}><HeartPulse/>หน้าหลัก</button><button className={view==='health'?'active':''} onClick={()=>setView('health')}><Activity/>ประวัติสุขภาพ</button><button className={view==='profile'?'active':''} onClick={()=>setView('profile')}><UserRound/>ฉัน</button></nav></div>;
}
function Metric({icon,label,value,unit}:{icon:React.ReactNode;label:string;value:string|number;unit:string}){return <div className="metric"><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{unit}</small></div>};
function Panel({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="panel"><div className="panel-head"><div className="panel-title">{icon}<h2>{title}</h2></div></div>{children}</section>};
function Row({label,value}:{label:string;value:string}){return <div className="record-row"><span>{label}</span><b>{value}</b></div>};
function Info({label,value}:{label:string;value:string}){return <div className="info"><span>{label}</span><b>{value}</b></div>};
